name: build-and-release
on:
  push:
    tags: ["v*.*.*"]           # fires on v1.2.3

jobs:
  tauri:
    runs-on: windows-latest

    # keep Cargo output and cache in the same custom folder
    env:
      CARGO_TARGET_DIR: wab2b-helper/target

    permissions:
      contents: write          # lets tauri-action draft & upload release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22     # you chose Current; fine if your deps build on 22
          check-latest: true
          cache: npm
          cache-dependency-path: wab2b-helper/package-lock.json

      # Rust cache (quoted mapping so YAML parses the arrow correctly)
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "wab2b-helper/backend -> ../target"

      - name: install app dependencies
        working-directory: wab2b-helper
        run: npm ci

      # build, updater-sign, draft release, upload MSI + latest.json
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN:                       ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY:          ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: wab2b-helper/backend
          tagName:        ${{ github.ref_name }}
          releaseName:    "v${{ github.ref_name }}"
          releaseDraft:   true
          releaseBody:    'See the assets to download this version and install.'
          prerelease:     false
