name: Build & Release

on:
  push:
    tags: ["v*"]          # e.g. v1.0.3, v2.1.0-beta

jobs:
  build:
    runs-on: windows-latest

    env:
      TAURI_SIGNING_PRIVATE_KEY:          ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    steps:
    ########################################################
    # 1 ▸ Check out code
    ########################################################
    - uses: actions/checkout@v4

    ########################################################
    # 2 ▸ Install Node (with sub-folder cache)
    ########################################################
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*                     # latest LTS :contentReference[oaicite:5]{index=5}
        cache: npm
        cache-dependency-path: wab2b-helper/package-lock.json

    ########################################################
    # 3 ▸ Install deps
    ########################################################
    - name: Install dependencies
      working-directory: wab2b-helper
      run: npm ci

    ########################################################
    # 4 ▸ Build the Tauri app (signed)
    ########################################################
    - name: Build (npm run tauri:build)
      working-directory: wab2b-helper
      env:
        TAURI_SIGNING_PRIVATE_KEY:          ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      run: npm run tauri:build              # ← exactly what you requested

    ########################################################
    # 5 ▸ Publish the release & upload binaries
    ########################################################
    - name: Publish GitHub release
      uses: softprops/action-gh-release@v2   # easy asset uploader :contentReference[oaicite:6]{index=6}
      if: github.ref_type == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:    ${{ github.ref_name }}
        name:        "WAB2B Helper ${{ github.ref_name }}"
        draft:       false
        prerelease:  false
        body: |
          # WAB2B Helper ${{ github.ref_name }}

          Release date: 12 July 2025  
          (tag `${{ github.ref_name }}`)

          ---

          ## ✨ Features
          1. **Deep-Link Attachment Handler**  
             • Handles `wab2b-helper:<url>` links fired from any browser.  
             • Detects file type (image / video / document) instantly.  
             • One-click actions: **Copy**, **Download & Save**, auto-open file.

          2. **Automatic Updater**  
             • Background check at startup + manual “Refresh” button.  
             • Secure update pipeline via GitHub Releases + ed25519 signature.  
             • Download progress bar, toast prompts, single-click install & restart.

          3. **Dark / Light Theme Toggle**  
             • Smooth transition using Tailwind CSS variables.  
             • Remembers preference between launches.

          4. **Toast Notification System**  
             • Reusable React component (success / error).  
             • Queueing, auto-dismiss, manual close.

          ---

          ## 🛠 Technical Highlights
          * **Tauri v2.6** backend, **React 19 + Vite** frontend.  
          * CI/CD: GitHub Actions builds, signs, publishes installers + `latest.json`.  
          * Windows NSIS + MSI bundles provided; updater artifacts signed.  
          * Codebase updated to Rust 2024 edition; all deps on latest stable versions.

          ---

          ## 🚀 Getting Started
          1. Download `wab2b-helper_${{ github.ref_name }}_x64-setup.exe` from the assets below.  
          2. Install and launch.  
          3. Test deep-links: open a browser and navigate to  
             ```
             wab2b-helper:https://example.com/demo.pdf
             ```  
             The attachment panel will appear instantly.

          Enjoy!  If you run into issues, open an issue on GitHub or email support@wab2b.com.
        files: |
          wab2b-helper/target/release/**/*.exe
          wab2b-helper/target/release/**/*.msi
