name: Build & Release

on:
  push:
    tags: [ "v*" ]      # v1.0.2, v2.1.0-beta, …

jobs:
  build:
    runs-on: windows-latest
    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    steps:
      # 1. Get the code
      - uses: actions/checkout@v4

      # 2. Install Node + npm and enable cache for *our* lock-file
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: wab2b-helper/package-lock.json   # <── key fix

      # 3. Install JS deps inside sub-folder
      - name: npm ci
        run: npm ci
        working-directory: wab2b-helper

      # 4. Build, sign and publish the release
      - name: Build & publish
        uses: tauri-apps/tauri-action@v0
        with:
          # tell the action where the Tauri project lives
          projectPath: wab2b-helper
          tagName:       ${{ github.ref_name }}
          releaseName:   "WAB2B Helper ${{ github.ref_name }}"
          includeUpdaterJson: true
          releaseDraft:  false
          # optional changelog text
          releaseBody: |
            ### Changelog
            - Automatic updater enabled
            - Attachment handler improvements
            - Dark-mode toggle
            - etc…