name: Build & Release

on:
  push:
    tags: [ "v*" ]      # v1.0.2, v2.1.0-beta, …

jobs:
  build:
    runs-on: windows-latest
    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    steps:
      # 1. Get the code
      - uses: actions/checkout@v4

      # 2. Install Node + npm and enable cache for *our* lock-file
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: wab2b-helper/package-lock.json   # <── key fix

      # 3. Install JS deps inside sub-folder
      - name: npm ci
        run: npm ci
        working-directory: wab2b-helper

      # 4. Build, sign and publish the release
      - name: Build & publish
        uses: tauri-apps/tauri-action@v0
        with:
          # tell the action where the Tauri project lives
          projectPath: wab2b-helper
          tagName:       ${{ github.ref_name }}
          releaseName:   "WAB2B Helper ${{ github.ref_name }}"
          includeUpdaterJson: true
          releaseDraft:  false
          tauriScript: "npm run tauri:build"   # run our custom build script
          # optional changelog text
          releaseBody: |
            # WAB2B Helper ${{ github.ref_name }}

            Release date: 12 July 2025  
            (tag `${{ github.ref_name }}`)

            ---

            ## ✨ Features
            1. **Deep-Link Attachment Handler**  
               • Handles `wab2b-helper:<url>` links fired from any browser.  
               • Detects file type (image / video / document) instantly.  
               • One-click actions: **Copy**, **Download & Save**, auto-open file.

            2. **Automatic Updater**  
               • Background check at startup + manual “Refresh” button.  
               • Secure update pipeline via GitHub Releases + ed25519 signature.  
               • Download progress bar, toast prompts, single-click install & restart.

            3. **Dark / Light Theme Toggle**  
               • Smooth transition using Tailwind CSS variables.  
               • Remembers preference between launches.

            4. **Toast Notification System**  
               • Reusable React component (success / error).  
               • Queueing, auto-dismiss, manual close.

            ---

            ## 🛠 Technical Highlights
            * **Tauri v2.6** backend, **React 19 + Vite** frontend.  
            * CI/CD: GitHub Actions builds, signs, publishes installers + `latest.json`.  
            * Windows NSIS + MSI bundles provided; updater artifacts signed.  
            * Codebase updated to Rust 2024 edition; all deps on latest stable versions.

            ---

            ## 🚀 Getting Started
            1. Download `wab2b-helper_${{ github.ref_name }}_x64-setup.exe` from the assets below.  
            2. Install and launch.  
            3. Test deep-links: open a browser and navigate to  
               ```
               wab2b-helper:https://example.com/demo.pdf
               ```  
               The attachment panel will appear instantly.

            Enjoy!  If you run into issues, open an issue on GitHub or email support@wab2b.com.