name: Publish Tauri App
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: wab2b-helper/package-lock.json

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, rustfmt, clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: 'wab2b-helper/backend -> wab2b-helper/backend/target'

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install dependencies
        working-directory: ./wab2b-helper
        run: npm ci

      - name: Build the app
        working-directory: ./wab2b-helper
        shell: pwsh
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          # Build with verbose output to see signing process
          tauri build --bundles msi --bundles nsis --config backend/tauri.conf.json --verbose
          
          # Verify .sig files were created
          if (-not (Test-Path "backend/target/release/wab2b-helper.sig")) {
            Write-Error "No .sig file was generated. Check your signing configuration."
            exit 1
          }

      - name: Verify artifacts
        shell: pwsh
        run: |
          # Check if all required files exist
          if (-not (Test-Path "wab2b-helper/backend/target/release/wab2b-helper.sig")) {
            Write-Error "Missing .sig file"
            Get-ChildItem -Path "wab2b-helper/backend/target/release/"
            exit 1
          }

          $version = (Get-Content -Raw -Path wab2b-helper/package.json | ConvertFrom-Json).version
          $msiPath = "wab2b-helper/backend/target/release/bundle/msi/WAB2B Helper_${version}_x64_en-US.msi"
          $nsisPath = "wab2b-helper/backend/target/release/bundle/nsis/WAB2B Helper_${version}_x64-setup.exe"

          if (-not (Test-Path $msiPath)) {
            Write-Error "Missing MSI installer at path: $msiPath"
            exit 1
          }
          
          if (-not (Test-Path $nsisPath)) {
            Write-Error "Missing NSIS installer at path: $nsisPath"
            exit 1
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            wab2b-helper/backend/target/release/bundle/msi/*.msi
            wab2b-helper/backend/target/release/bundle/nsis/*.exe
            wab2b-helper/backend/target/release/*.sig
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wab2b-helper/backend/target/release/bundle/msi/*.msi
            wab2b-helper/backend/target/release/bundle/nsis/*.exe
            wab2b-helper/backend/target/release/*.sig
          body: |
            ## v1.0.3 - 2025-07-14

            ### 🚀 New Features
            - Added cross-env for Windows compatibility
            - Enabled NSIS bundling for Windows installers

            ### 🐛 Bug Fixes
            - Fixed CI/CD pipeline configuration
            - Resolved build script issues
            - Removed duplicate build arguments

            ### 🛠️ Development
            - Updated Tauri action to @dev for better updater support
            - Cleaned up package.json scripts
            - Improved build process reliability

            ### 📦 Dependencies
            - Added cross-env v7.0.3
            - Updated Tauri-related dependencies

            ### 📝 Notes
            - This release focuses on improving the build process and Windows compatibility
            - The application now includes a proper NSIS installer for Windows
            - Auto-update functionality has been enhanced with proper signing

            ## How to Update
            - Download the latest installer from the release assets
            - The application will automatically check for updates on startup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: wab2b-helper
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          releaseBody: 'See the assets to download this version and install.'
          prerelease: false
          args: --config backend/tauri.conf.json
          includeUpdaterJson: true