name: build-and-release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  tauri:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # ➋  Fast compiles: installs sccache & wires GHA-cache
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9         # :contentReference[oaicite:0]{index=0}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: npm
          cache-dependency-path: wab2b-helper/package-lock.json

      # ➌  Cache the Rust build artifacts
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "wab2b-helper/backend -> target"

      - name: install app dependencies
        working-directory: wab2b-helper
        run: npm ci

      # ➍  Release with Tauri Action
      - uses: tauri-apps/tauri-action@v0.5.22
        env:
          GITHUB_TOKEN:                       ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY:          ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: wab2b-helper
          tagName:      ${{ github.ref_name }}
          releaseName:  ${{ github.ref_name }}
          releaseDraft: false
          releaseBody:  'See the assets to download this version and install.'
          prerelease:   false
          args: --config backend/tauri.conf.json